In [1]:
import pandas as pd
import numpy as np
import math
from scipy import stats
from scipy.stats import ttest_ind

# HYPOTHESIS TESTING CUTLETS

In [2]:
data = pd.read_csv(r"C:\Users\mukes\OneDrive\Desktop\Data Science\Assignments\Hypothesis Testing\Cutlets.csv") 

In [3]:
data.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

# Calculate the sample means and standard deviations for Unit A and Unit B.

In [13]:
data['Unit A'].mean()

7.0190914285714285

In [50]:
data['Unit B'].mean()

6.964297142857142

In [6]:
data['Unit A'].std()

0.2884084841815496

In [7]:
data['Unit B'].std()

0.343400647063108

# Conduct the t-test

In [14]:
unit_a_data = data['Unit A']
unit_b_data = data['Unit B']
t_statistic, p_value = stats.ttest_ind(unit_a_data, unit_b_data)
print("t-statistic:", t_statistic)
print("p-value:", p_value)

t-statistic: 0.7228688704678063
p-value: 0.4722394724599501


In [11]:
# Based on the analysis, there is not enough evidence to conclude that there is a significant difference in the diameter of the
# cutlets between Unit A and Unit B at the 5% significance level.

# HYPOTHESIS TESTING LABTAT

In [13]:
from scipy.stats import f_oneway

In [15]:
data = pd.read_csv(r"C:\Users\mukes\OneDrive\Desktop\Data Science\Assignments\Hypothesis Testing\LabTAT.csv")
data.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

# Conducting F Test

In [17]:
unit_a_data = data['Laboratory 1']
unit_b_data = data['Laboratory 2']
unit_c_data = data['Laboratory 3']
unit_d_data = data['Laboratory 4']

# Perform one-way ANOVA
f_statistic, p_value = f_oneway(unit_a_data, unit_b_data, unit_c_data, unit_d_data)
print("F-statistic:", f_statistic)
print("P-value:", p_value)

F-statistic: 118.70421654401437
P-value: 2.1156708949992414e-57


In [ ]:
# There is no significant difference in the average TAT among the different laboratories.

# HYPOTHESIS TESTING BUYER RATIO


# Chi Square Test

In [23]:
from scipy.stats import chi2_contingency
observed_data = np.array([[50, 435], [142, 1523], [131, 1356], [70, 750]])
# data = [[50, 435], [142, 1523], [131, 1356], [70, 750]]

# Perform chi-square test for independence
chi2_stat, p_value, dof, expected = chi2_contingency(observed_data)

# Print the results
print("Chi2 Statistic:", chi2_stat)
print("P-value:", p_value)
print("Degrees of Freedom:", dof)
print("Expected Frequencies Table:")
print(expected)

Chi2 Statistic: 1.5959455386610577
P-value: 0.6603094907091882
Degrees of Freedom: 3
Expected Frequencies Table:
[[  42.76531299  442.23468701]
 [ 146.81287862 1518.18712138]
 [ 131.11756787 1355.88243213]
 [  72.30424052  747.69575948]]


In [ ]:
# The p-value 0.6 is greater than 0.05
# Thherefore, the sales of products does not show variations in male-female buyer ratios across the East, West, North, and South
# regions. 

# HYPOTHESIS TESTING: CUSTOM ORDER FORM

In [24]:
from scipy.stats import chi2_contingency
data = pd.read_csv(r"C:\Users\mukes\OneDrive\Desktop\Data Science\Assignments\Hypothesis Testing\Costomer+OrderForm.csv")
data.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

# Chi Square Test

In [21]:
import numpy as np
from scipy.stats import chi2_contingency

# Data
center_data = [
    ["defective", "non-defective"],
    ["defective", "defective"],
    ["non-defective", "non-defective"],
    ["defective", "non-defective"]
]

# Convert string data to numerical format
defective_counts = [row.count("defective") for row in center_data]
non_defective_counts = [row.count("non-defective") for row in center_data]

# Create a contingency table
data = np.array([defective_counts, non_defective_counts])

# Perform the chi-square test
chi2, p, dof, expected = chi2_contingency(data)

# Output the results
print(f"Chi-square statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected frequencies:")
print(expected)

# Compare p-value to significance level (0.05)
if p < 0.05:
    print("Reject the null hypothesis. There is evidence that the defective percentage varies by center.")
else:
    print("Fail to reject the null hypothesis. There is no significant evidence that the defective percentage varies by center.")

Chi-square statistic: 4.0
P-value: 0.26146412994911117
Degrees of freedom: 3
Expected frequencies:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Fail to reject the null hypothesis. There is no significant evidence that the defective percentage varies by center.
